version: "3.9"

services:
  app:
    build: .
    container_name: crypto-etl-app
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=YOUR_PASSWORD
      - DB_NAME=crypto
      - DB_PORT=3306
    volumes:
      - .:/app
    networks:
      - crypto-net

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=YOUR_PASSWORD
      - MYSQL_DATABASE=crypto
    ports:
      - "3306:3306"
    networks:
      - crypto-net

networks:
  crypto-net:
